frontend:
  image: frontend-image:dev
  replicas: 1
  serviceType: ClusterIP
  servicePort: 80

backend:
  image: backend-image:dev
  replicas: 1
  serviceType: ClusterIP
  servicePort: 8080

database:
  image: database-image:dev
  replicas: 1
  serviceType: ClusterIP
  servicePort: 5432
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
