apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-database
spec:
  type: {{ .Values.database.serviceType }}
  ports:
    - port: {{ .Values.database.servicePort }}
      targetPort: 5432
  selector:
    app: {{ include "my-app.name" . }}
    component: database
