apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: 80
  selector:
    app: {{ include "my-app.name" . }}
    component: frontend
